### ISSUE TITLE
Bug when calculating worst scenario

### ISSUE THREAD

**Issue by stephan-hutter** [papaemmelab/ipssm#1]
Hi!

I came accross a bug when the worst scenario is calculated in the case of missing data.
The values for `IPSSMscore_worst` often look exactly like those for `IPSSMscore_best`.

I think I located the source of the problem: There is a typo in line 74 of `IPSSMmain.R`:

```
 xworst <- FillScenario(x, imputeValues=bestValues, scenario="worst") 
```` 

The `imputeValues` parameter here should probably be `worstValues` instead of  `bestValues`.

Hope this fixes it.

Cheers,
Stephan

**Comment by ElsaB** [comment]
Hi Stephan,

You are right! well spotted!

Thanks for checking the R package.
Also very brave of you to go through it as I still need to add a proper
vignette etc :)
Any other comments please let me know!

Just committed the change.

FYI, the reason why in some cases you may still had best != worst was
because the bug affected missing data in the main variables but not the
residual genes.

Thanks again!
Elsa

**Comment by stephan-hutter** [comment]
Hi Elsa,

everything now looks fine on our side.

Thanks for the fast fix!

Cheers,
Stephan
